# cdnProvider(CDN提供商)支持: aliyun (阿里云)、tencent (腾讯云)、huawei(华为云)
# dnsProvider(DNS供应商)支持: 名称参考 https://go-acme.github.io/lego/dns/ 
# caProvider(CA供应商)支持:   letsencrypt（Let's Encrypt）、buypass（Buypass）、zerossl（ZeroSSL）
spec:
  - cdnProvider: aliyun
    description: "CDN提供商是阿里云，使用的加速域名提供商是阿里云、腾讯云"
    dns:
      - provider: alidns
        caProvider: ''    # 默认值为'letsencrypt'，也可以不写该字段
        domains:
          - test1.cn           # 二级域名
          - www.test2.com      # 全域名
      - provider: tencentcloud
        domains:
          - "test1.net"

  - cdnProvider: tencent
    description: "CDN提供商是腾讯云，使用的加速域名提供商是cloudFlare、route53"
    dns:
      - provider: cloudflare
        caProvider: "zerossl"
        domains:
          - test1.xyz
      - provider: route53
        domains:
          - test1.io

  - cdnProvider: huawei
    description: "CDN提供商是华为云，使用的加速域名提供商是阿里云、Google Cloud"
    dns:
      - provider: gcloud
        caProvider: "zerossl"
        domains:
          - test1.org
